/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { College, WeeklyNote, VisitLog } from './types';

export const INITIAL_COLLEGES: College[] = [
  {
    id: 'c_dy_patil',
    name: 'D. Y. Patil Medical College',
    type: 'active',
    studentCount: 820,
    revenue: 11200000,
    renewalDueDate: '2026-06-30',
    isLapsed: true,
    lmsStatus: 'Provided',
    courseProgress: 88,
    assessmentsConducted: 45,
    hoursWatched: 1250,
    smartLibraryStatus: 'Active',
    eBooksAccessed: 2400,
    physicalCheckouts: 420,
    activeReaders: 550,
    v5Status: 'Provided',
    v5Address: 'Sector 7, Nerul, Navi Mumbai, Maharashtra 400706',
    v5Date: '2026-05-10',
    v5ReceiptConfirmed: 'Done',
    facultyDemoConducted: 4,
    facultyDemoConductedDate: '2026-04-12',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Initial demo completed successfully. All departments onboarded.']
  },
  {
    id: 'c_ramachandra',
    name: 'Sri Ramachandra Medical College & Research Institute',
    type: 'active',
    studentCount: 910,
    revenue: 12500000,
    renewalDueDate: '2026-03-02',
    isLapsed: true,
    lmsStatus: 'Provided',
    courseProgress: 92,
    assessmentsConducted: 58,
    hoursWatched: 1890,
    smartLibraryStatus: 'Active',
    eBooksAccessed: 3100,
    physicalCheckouts: 560,
    activeReaders: 680,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 5,
    facultyDemoConductedDate: '2026-02-18',
    facultyDemoAligned: 1,
    facultyDemoAlignedDate: '2026-06-15',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Requires renewal sign-off from Dean. Follow-up meeting scheduled.']
  },
  {
    id: 'c_icare',
    name: 'ICARE Institute of Medical Sciences & Research, Haldia, Purba Midnapore',
    type: 'active',
    studentCount: 580,
    revenue: 8450000,
    renewalDueDate: '2026-06-15',
    isLapsed: true,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'Banbishnupur, Haldia, West Bengal 721645',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 2,
    facultyDemoAlignedDate: '2026-06-10',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Agreement signed but implementation delayed due to local holidays.']
  },
  {
    id: 'c_rama',
    name: 'Rama Medical College and Hospital',
    type: 'active',
    studentCount: 460,
    revenue: 5600000,
    renewalDueDate: '2026-03-23',
    isLapsed: true,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 1,
    facultyDemoConductedDate: '2026-01-20',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Renewal pending management approval. Sent reminder.']
  },
  {
    id: 'c_gems',
    name: 'GEMS, Srikakulam',
    type: 'active',
    studentCount: 520,
    revenue: 6780000,
    renewalDueDate: '2026-03-31',
    isLapsed: true,
    lmsStatus: 'Provided',
    courseProgress: 76,
    assessmentsConducted: 21,
    hoursWatched: 890,
    smartLibraryStatus: 'Active',
    eBooksAccessed: 1540,
    physicalCheckouts: 210,
    activeReaders: 310,
    v5Status: 'Provided',
    v5Address: 'Ragolu, Srikakulam, Andhra Pradesh 532484',
    v5Date: '2026-02-14',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 3,
    facultyDemoConductedDate: '2026-01-15',
    facultyDemoAligned: 1,
    facultyDemoAlignedDate: '2026-06-25',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Dispatched physical v5 notes; awaiting delivery confirmation receipt.']
  },
  {
    id: 'c_smbt',
    name: 'SMBT',
    type: 'active',
    studentCount: 610,
    revenue: 8500000,
    renewalDueDate: '2027-03-23',
    isLapsed: false,
    lmsStatus: 'Provided',
    courseProgress: 65,
    assessmentsConducted: 34,
    hoursWatched: 720,
    smartLibraryStatus: 'Active',
    eBooksAccessed: 1200,
    physicalCheckouts: 190,
    activeReaders: 280,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 5400000,
    pendingPaymentDueDate: '2027-03-23',
    remarks: ['Awaiting part payment clearance. Main contract is locked.']
  },
  {
    id: 'c_balaji',
    name: 'Sri Balaji Medical College, Hospital and Research Institute',
    type: 'active',
    studentCount: 580,
    revenue: 7250000,
    renewalDueDate: '2029-11-03',
    isLapsed: false,
    lmsStatus: 'Provided',
    courseProgress: 82,
    assessmentsConducted: 41,
    hoursWatched: 1100,
    smartLibraryStatus: 'Active',
    eBooksAccessed: 2100,
    physicalCheckouts: 380,
    activeReaders: 490,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 2,
    facultyDemoConductedDate: '2025-11-12',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 3074500,
    pendingPaymentDueDate: '2029-11-03',
    remarks: ['Long term agreement. Pending balance installment schedule.']
  },
  {
    id: 'c_navodaya',
    name: 'Navodaya Medical College',
    type: 'active',
    studentCount: 512,
    revenue: 5800000,
    renewalDueDate: '2026-11-13',
    isLapsed: false,
    lmsStatus: 'Provided',
    courseProgress: 59,
    assessmentsConducted: 18,
    hoursWatched: 490,
    smartLibraryStatus: 'Active',
    eBooksAccessed: 950,
    physicalCheckouts: 120,
    activeReaders: 190,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 4285800,
    pendingPaymentDueDate: '2026-11-13',
    remarks: ['Active but pending final payment clearances due soon.']
  },
  {
    id: 'c_alluri',
    name: 'Alluri Sita Rama Academy of Medical Sciences',
    type: 'active',
    studentCount: 490,
    revenue: 6500000,
    renewalDueDate: '2026-08-15',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Onboarding scheduled for early next month.']
  },
  {
    id: 'c_ananta',
    name: 'Ananta Institute of Medical Sciences & Research Centre, Rajsamand',
    type: 'active',
    studentCount: 382,
    revenue: 5200000,
    renewalDueDate: '2026-09-20',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  {
    id: 'c_bhaskar',
    name: 'Bhaskar Medical College',
    type: 'active',
    studentCount: 350,
    revenue: 4550000,
    renewalDueDate: '2026-10-18',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  {
    id: 'c_mkshah',
    name: 'Dr. MK Shah Medical College & Research Centre',
    type: 'active',
    studentCount: 446,
    revenue: 6820000,
    renewalDueDate: '2026-12-05',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  {
    id: 'c_gsl',
    name: 'GSL Medical College',
    type: 'active',
    studentCount: 410,
    revenue: 6100000,
    renewalDueDate: '2026-07-22',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  {
    id: 'c_hitech_bhu',
    name: 'Hi-Tech Medical College & Hospital, Bhubaneswar',
    type: 'active',
    studentCount: 380,
    revenue: 5800000,
    renewalDueDate: '2026-08-30',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  {
    id: 'c_hitech_rour',
    name: 'Hi-Tech Medical College & Hospital, Rourkela',
    type: 'active',
    studentCount: 345,
    revenue: 5400000,
    renewalDueDate: '2026-09-12',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  {
    id: 'c_kamineni_acad',
    name: 'Kamineni Academy of Medical Sciences',
    type: 'active',
    studentCount: 550,
    revenue: 7900000,
    renewalDueDate: '2026-07-04',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  {
    id: 'c_kamineni_inst',
    name: 'Kamineni Institute of Medical Sciences',
    type: 'active',
    studentCount: 660,
    revenue: 3296056, // Combined with other active colleges to sum up EXACTLY to ₹11,39,46,056
    renewalDueDate: '2026-10-10',
    isLapsed: false,
    lmsStatus: 'Not Provided',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: []
  },
  // Active colleges list finishes with 17 items (17 elements total in active pipeline state)
  // Let's add pipeline (prospective) items
  {
    id: 'p_maharshi',
    name: 'Maharshi Markandey University',
    type: 'pipeline',
    studentCount: 450,
    revenue: 5500000,
    renewalDueDate: '2026-12-01',
    isLapsed: false,
    lmsStatus: 'Pending',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 1,
    facultyDemoAlignedDate: '2026-06-12',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Follow-up call scheduled next Tuesday to finalize paper drafts.']
  },
  {
    id: 'p_nimra',
    name: 'NIMRA Institute of Medical Sciences',
    type: 'pipeline',
    studentCount: 520,
    revenue: 6200000,
    renewalDueDate: '2026-11-15',
    isLapsed: false,
    lmsStatus: 'Pending',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 2,
    facultyDemoAlignedDate: '2026-06-18',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Board meeting called to discuss DocTutorials subscription packages.']
  },
  {
    id: 'p_mvj',
    name: 'MVJ Medical College',
    type: 'pipeline',
    studentCount: 480,
    revenue: 5800000,
    renewalDueDate: '2026-12-10',
    isLapsed: false,
    lmsStatus: 'Pending',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 1,
    facultyDemoAlignedDate: '2026-06-20',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Draft agreement sent to director. High closures probability.']
  },
  {
    id: 'p_gayatri',
    name: 'Gayatri Vidya Parishad Medical College',
    type: 'pipeline',
    studentCount: 460,
    revenue: 5200000,
    renewalDueDate: '2026-11-20',
    isLapsed: false,
    lmsStatus: 'Pending',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Awaiting response on localized pricing models.']
  },
  {
    id: 'p_kims_ama',
    name: 'KIMS Amalapuram',
    type: 'pipeline',
    studentCount: 500,
    revenue: 5900000,
    renewalDueDate: '2026-12-05',
    isLapsed: false,
    lmsStatus: 'Pending',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 2,
    facultyDemoAlignedDate: '2026-06-28',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Demo requested for PG clinical modules specifically.']
  },
  {
    id: 'p_gsl_pipe',
    name: 'GSL Medical College (Prospective)',
    type: 'pipeline',
    studentCount: 420,
    revenue: 4800000,
    renewalDueDate: '2026-11-30',
    isLapsed: false,
    lmsStatus: 'Pending',
    courseProgress: 0,
    assessmentsConducted: 0,
    hoursWatched: 0,
    smartLibraryStatus: 'Inactive',
    eBooksAccessed: 0,
    physicalCheckouts: 0,
    activeReaders: 0,
    v5Status: 'Not Provided',
    v5Address: 'N/A',
    v5Date: 'N/A',
    v5ReceiptConfirmed: 'Pending',
    facultyDemoConducted: 0,
    facultyDemoConductedDate: 'N/A',
    facultyDemoAligned: 0,
    facultyDemoAlignedDate: 'N/A',
    pendingPaymentAmount: 0,
    pendingPaymentDueDate: 'N/A',
    remarks: ['Initial meeting done. Standard presentation delivered.']
  }
];

export const INITIAL_WEEKLY_NOTES: WeeklyNote[] = [
  {
    id: 'n_01',
    type: 'college',
    collegeId: 'c_dy_patil',
    collegeName: 'D. Y. Patil Medical College',
    content: 'Completed the annual LMS training update with the senior academic staff. The Dean requested additional reports on assessment usage.',
    date: '2026-02-05',
    year: 2026,
    week: 5
  },
  {
    id: 'n_02',
    type: 'misc',
    content: 'Discussed national medical library updates. Initiated preparations for the V5 physical modules release for all Southern institutions.',
    date: '2026-02-04',
    year: 2026,
    week: 5
  },
  {
    id: 'n_03',
    type: 'college',
    collegeId: 'c_ramachandra',
    collegeName: 'Sri Ramachandra Medical College & Research Institute',
    content: 'Delivered smart library integration updates. Staff were trained on using digital study guides.',
    date: '2025-12-18',
    year: 2025,
    week: 51
  },
  {
    id: 'n_04',
    type: 'college',
    collegeId: 'c_ramachandra',
    collegeName: 'Sri Ramachandra Medical College & Research Institute',
    content: 'Dean requested a detailed timeline of student onboarding schedules.',
    date: '2025-12-19',
    year: 2025,
    week: 51
  },
  {
    id: 'n_05',
    type: 'misc',
    content: 'Quarterly compliance audit conducted for the Northern region servers.',
    date: '2025-12-20',
    year: 2025,
    week: 51
  },
  {
    id: 'n_06',
    type: 'college',
    collegeId: 'c_gems',
    collegeName: 'GEMS, Srikakulam',
    content: 'Delivered V5 Notes hardcopies. Receipt confirmation pending. Verified the LMS connection speed with local network administrator.',
    date: '2025-12-04',
    year: 2025,
    week: 49
  },
  {
    id: 'n_07',
    type: 'college',
    collegeId: 'c_smbt',
    collegeName: 'SMBT',
    content: 'Installed the Smart Library kiosk. Conducted trial runs with 50 students. Outstanding interest in the clinical flashcards module.',
    date: '2025-11-28',
    year: 2025,
    week: 48
  },
  {
    id: 'n_08',
    type: 'college',
    collegeId: 'c_navodaya',
    collegeName: 'Navodaya Medical College',
    content: 'Met with head of Pathology department. Aligned custom curriculum mappings within the core LMS.',
    date: '2025-11-20',
    year: 2025,
    week: 47
  }
];

export const INITIAL_VISIT_LOGS: VisitLog[] = [
  {
    id: 'v_01',
    collegeName: 'D. Y. Patil Medical College',
    representative: 'Nikhil Sathe',
    date: '2026-05-12',
    purpose: 'Onsite LMS configuration audit',
    feedback: 'Configured router parameters to speed up digital lecture stream buffering. Outstanding dean satisfaction.',
    status: 'Completed'
  },
  {
    id: 'v_02',
    collegeName: 'Maharshi Markandey University',
    representative: 'Reena Nair',
    date: '2026-05-18',
    purpose: 'Pipeline proposal pitch to Management Board',
    feedback: 'Proposal reviewed. Under strong consideration. Awaiting feedback on the regional licensing discounts.',
    status: 'Completed'
  },
  {
    id: 'v_03',
    collegeName: 'GEMS, Srikakulam',
    representative: 'K. Rajasekhar',
    date: '2026-05-25',
    purpose: 'V5 Modules distribution audit & local library setup',
    feedback: 'V5 hardcopies confirmed as received. Setting up interactive search terminal mapping tomorrow.',
    status: 'Completed'
  }
];
